version: '3.8'

services:
  # EngAgent API
  engagent-api:
    build: .
    container_name: engagent-api
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=engagent_user
      - MYSQL_PASSWORD=engagent_password
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=engagent_db
      - OLLAMA_MODEL=mistral
      - HF_EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
      - USE_VERTEX=false
    volumes:
      - ./data:/app/data
      - ./key:/app/key
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ngrok service to expose engagent-api
  ngrok:
    image: ngrok/ngrok:latest
    container_name: engagent-ngrok
    environment:
      # IMPORTANT: Replace with your ngrok auth token
      - NGROK_AUTHTOKEN=YOUR_NGROK_AUTHTOKEN
    command: http engagent-api:8000 --domain curiously-promoted-reptile.ngrok-free.app # <-- CHANGE THIS to your fixed domain
    depends_on:
      - engagent-api
    restart: unless-stopped
